name: Build for Linux

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfreetype-dev zlib1g-dev
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.*'
        modules: 'qtmultimedia'
      
    - name: build-for-linux
      run: ./scripts/rebuild_linux_with_gui.sh
      
    - uses: actions/upload-artifact@v4
      with:
         name: tsMuxer-linux
         path: bin/lnx.zip
      name: upload-artefact

    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/lnx.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
