name: Build for Windows 32-bit

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      name: checkout

    - name: Setup Qt6 Windows 7 (Qt6windows7)
      run: |
        $QT_ZIP = "${{ runner.temp }}\qt6.7z"
        $QT_PATH = "${{ runner.temp }}\qt6windows7"
        
        Write-Host "Downloading Qt6 Windows 7 compatible binaries (32-bit)..."
        $QT_URL = "https://github.com/crystalidea/qt6windows7/releases/download/v6.8.3/qt6_x86_to_run_on_windows7.7z"
        Write-Host "URL: $QT_URL"
        
        Invoke-WebRequest -Uri $QT_URL -OutFile $QT_ZIP
        
        Write-Host "Extracting Qt6 binaries..."
        mkdir $QT_PATH
        7z x $QT_ZIP -o"$QT_PATH" -y
        
        Write-Host "Qt6 path: $QT_PATH"
        Add-Content -Path $env:GITHUB_ENV -Value "CMAKE_PREFIX_PATH=$QT_PATH"

    - name: Build tsMuxer (32-bit)
      run: |
        mkdir build
        cd build
        cmake ../ -A Win32 -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" -DTSMUXER_GUI=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        
        if (!(Test-Path "../bin")) { mkdir "../bin" }
        Copy-Item -Path "tsMuxer/Release/tsmuxer.exe" -Destination "../bin/tsMuxeR.exe" -Force
        if (Test-Path "tsMuxerGUI/Release/tsmuxergui.exe") {
          Copy-Item -Path "tsMuxerGUI/Release/tsmuxergui.exe" -Destination "../bin/tsMuxerGUI.exe" -Force
        }
        cd ..

    - name: Package Build
      run: |
        cd bin
        if (Test-Path "tsMuxerGUI.exe") {
          7z a -y w32.zip tsMuxeR.exe tsMuxerGUI.exe
        } else {
          7z a -y w32.zip tsMuxeR.exe
        }

    - uses: actions/upload-artifact@v4
      with:
        name: tsMuxer-w32
        path: bin/w32.zip
      name: upload-artifact

    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/w32.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
